---
title: "ecGEMs"
author: "Xinmeng Liao"
date: "2025-04-02"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(xlsx)
library(ggpubr)
library(tidyr)
library(ggridges)
library(ggsignif)
library(DESeq2)
library(ComplexHeatmap)
library(colorRamp2)
library(tidyverse)
library(phyloseq)
library(vegan)
for (i in c("select","filter","mutate","rename","left_join")){
  conflicted::conflict_prefer(i,"dplyr")
}
conflicted::conflicts_prefer(stats::sd)
```

# 1. load DAs
```{r}
edger <- read.csv("DAs/5%samples/edgeR.txt",header = T,sep = "\t") %>% 
  rename(pvalue = PValue, padj = FDR, log2FoldChange = logFC)
deseq <- read.csv("DAs/both visits/DESeq2.txt",header = T,sep = "\t")

e <- edger %>% filter(FDR < 0.05) %>% 
  pull(classification) %>% unique()
d <- deseq %>% filter(padj < 0.05) %>% 
  pull(classification) %>% unique()
```

# 2. Create FVA network
```{r}
taxo.all <- read.csv('/Users/xinmengliao/Documents/Project/20241117_CMA_PD_ecGEMs/validation.taxo.txt',header = T,sep = "\t") %>% 
  mutate(species = sapply(strsplit(split = "s__",classification),`[`,2)) %>%  
  filter(!is.na(species))
fva.all <- read.csv('/Users/xinmengliao/Documents/Project/20241117_CMA_PD_ecGEMs/validation.fva.nozero95.txt',sep = "\t",header = T)
#fva.all <- read.csv('/Users/xinmengliao/Documents/Project/20241117_CMA_PD_ecGEMs/validation.fva.all95.txt',sep = "\t",header = T)
mapread <- read.csv("abundance/abundance.mapped.txt",header = T,sep = "\t") 

length(unique(fva.all$sample)) # should be 46
res <- edger

mapped <- mapread %>% 
  left_join(., taxo.all %>% select(sample, user_genome, classification), by = c("sample","bin" = "user_genome")) %>% 
  filter(!is.na(classification))

create.network <- function(data, taxo.data, pvalue, padj, log2fc){
  data1 <- data %>% 
    left_join(., taxo.data %>% select(user_genome, sample, classification), by  = c("sample","bin" = "user_genome")) %>% 
    filter(!is.na(classification)) %>% 
    left_join(., res,by = c("classification")) %>% distinct() %>% 
    filter(!is.na(.data[[pvalue]])) 
  
  secrete <- data1 %>% filter(direction == "Secrete") %>%
    select(classification,exchangeRxns,direction,all_of(pvalue),all_of(padj),all_of(log2fc))  %>% 
    unique() %>% 
    dplyr::rename(Vertex.A = classification, Vertex.B = exchangeRxns) %>% 
    mutate(Type.A = "Microbe", Type.B = "Metabolite")
  network <- data1 %>% filter(direction != "Secrete") %>% 
    select(exchangeRxns,classification,direction,all_of(pvalue),all_of(padj),all_of(log2fc)) %>% 
    unique() %>% 
    dplyr::rename(Vertex.A = exchangeRxns, Vertex.B = classification) %>% 
    mutate(Type.A = "Metabolite", Type.B = "Microbe") %>% 
    rbind(., secrete) %>% 
    unique() %>% 
    filter(!is.na(.data[[padj]])) %>% 
    filter(Vertex.A != Vertex.B) %>% 
    group_by(edge_group = paste(pmin(Vertex.A, Vertex.B), pmax(Vertex.A, Vertex.B))) %>%
    filter(n() == 1) %>% 
    ungroup() %>% 
    select(-edge_group) %>% 
    select(Vertex.A, Type.A, Vertex.B, Type.B,everything())
  return(list(network, data1))
}

network.all <- create.network(fva.all,taxo.data = taxo.all,pvalue = "pvalue",padj = "padj",log2fc = "log2FoldChange")[1] %>% as.data.frame()
network.uptake <- network.all %>% filter(direction == "Uptake")
fva.all1 <- create.network(fva.all,taxo.data = taxo.all,pvalue = "pvalue",padj = "padj",log2fc = "log2FoldChange")[2] %>% as.data.frame()
```

# 3. Reporter metabolites
```{r}
rma <- function(network,pvalue,logFC, reaction,abundance = NULL){
  
  # change the microbe pvalue into z-score
  #network = network.uptake
  network <- network %>% 
    filter(!is.na(.data[[pvalue]])) %>%
    mutate(p.value = case_when(.data[[logFC]] > 0 ~ .data[[pvalue]] / 2,
                              .data[[logFC]]  == 0 ~ .data[[pvalue]] ,
                              .data[[logFC]]  < 0 ~ 1-(.data[[pvalue]]/2), TRUE ~ NA)) %>%
    mutate(zscore = qnorm(1 - p.value)) %>%  
    mutate(zscore = ifelse(is.na(zscore), 0, zscore)) %>% 
    mutate(zscore = case_when(zscore == -Inf ~ -15,
                              zscore == Inf ~ 15, TRUE ~ zscore)) %>% 
    mutate(zscore_direction = case_when(direction == "Uptake" ~ -1 * zscore,
                                        direction == "Secrete" ~ 1 * zscore, TRUE ~ NA)) %>% 
    mutate(detail = case_when(.data[[logFC]]  > 0 ~ "Increased", 
                            .data[[logFC]]  == 0 ~ "Unchanged",
                            .data[[logFC]]  < 0 ~ "Decreased", TRUE ~ NA),
           detail = case_when(direction == "Uptake" ~ paste(detail, "Uptake",sep = " + "), 
                               direction == "Secrete" ~ paste(detail, "Secrete",sep = " + "), TRUE ~ NA))

  
  mets <- unique(c(network %>% filter(Type.A == "Metabolite") %>% pull(Vertex.A),
                   network %>% filter(Type.B == "Metabolite") %>% pull(Vertex.B)))
  
  # calculate weight average
  if (!is.null(abundance)){
    mapped_ctrl <- abundance %>%  filter(grepl("Visit1",sample)) 
    avg <- mapped_ctrl %>% group_by(classification) %>% summarise(avg = sum(relative.abundance)/n_distinct(sample),.groups = "drop")
    total_avg = sum(avg$avg)
  }

  # calculate weighted zscores
  n_mets <- length(unique(mets))
  n_microbe <- rep(NA, n_mets)
  metZScores <- rep(NA, n_mets)
  metNGenes <- rep(NA, n_mets)
  meanZ <- rep(NA, n_mets)
  stdZ <- rep(NA, n_mets)
  microbe.zscore.list <- list()

  for (i in 1:n_mets){
    if(!is.null(abundance)){
       met.network <- network %>% 
          filter(Vertex.A == mets[i] | Vertex.B == mets[i]) %>% unique() %>% 
          left_join(., avg, by = c("Vertex.A" = "classification")) %>% 
          rename(mapped_VA = avg) %>%
          left_join(., avg, by = c("Vertex.B" = "classification")) %>%
          rename(mapped_VB = avg) %>%
          mutate(avg = coalesce(mapped_VA, mapped_VB)) %>% select(-mapped_VB,-mapped_VA) %>% 
          mutate(weight = avg / total_avg) %>% 
          mutate(zscore_predcmb = zscore_direction * weight) %>% unique()
       metZScores[i] <- sum(met.network$zscore_predcmb) / sqrt(nrow(met.network))
       meanZ[i] <- mean(met.network$zscore_predcmb)
       stdZ[i] <- sd(met.network$zscore_predcmb)
       metNGenes[i] <- mets[i]
       n_microbe[i] <- nrow(met.network)
       microbe.zscore.list[[i]] <- met.network$zscore_predcmb %>% unlist()
    }else{
       met.network <- network %>% 
        filter(Vertex.A == mets[i] | Vertex.B == mets[i]) %>% unique() 
       metZScores[i] <- sum(met.network$zscore_direction) / sqrt(nrow(met.network))
       meanZ[i] <- mean(met.network$zscore_direction)
       stdZ[i] <- sd(met.network$zscore_direction)
       metNGenes[i] <- mets[i]
       n_microbe[i] <- nrow(met.network)
       microbe.zscore.list[[i]] <- met.network$zscore_direction %>% unlist()
    }
  }
 
  # Filter out NA scores
  valid_mets <- which(!is.na(metZScores))
  mets <- mets[valid_mets]
  n_microbe <- n_microbe[valid_mets]
  metZScores <- metZScores[valid_mets]
  metNGenes <- metNGenes[valid_mets]
  meanZ <- meanZ[valid_mets]
  stdZ <- stdZ[valid_mets]
  
  # Background correction
  set.seed(42)
  n_sim <- 1000
  #n_sim <- 100000
  all_zscores <- unlist(microbe.zscore.list)
  
  # Precompute background stats for each k
  unique_k <- unique(n_microbe)
  background_means <- numeric(length(unique_k))
  background_sds <- numeric(length(unique_k))
  names(background_means) <- names(background_sds) <- unique_k
  
  background_scores_list <- list()

  for (j in seq_along(unique_k)) {
    k <- unique_k[j]
    sampled_scores <- replicate(n_sim, {
      sampled_zs <- sample(all_zscores, k, replace = TRUE)
      random_dirs <- ifelse(runif(k) < 0.5, 1, -1)
      directional_zs <- sampled_zs * random_dirs
      sum(directional_zs) / sqrt(k)
    })
    background_means[j] <- mean(sampled_scores)
    background_sds[j] <- sd(sampled_scores)
    background_scores_list[[as.character(k)]] <- sampled_scores
  }

  # Apply background correction using precomputed means and sds
  Z_corrected <- numeric(length(metZScores))
  p_corrected <- numeric(length(metZScores))
  
  for (m in seq_along(metZScores)) {
    k <- as.character(n_microbe[m])
    mu_k <- background_means[k]
    sigma_k <- background_sds[k]
    Z_corrected[m] <- (metZScores[m] - mu_k) / sigma_k
    p_corrected[m] <- ifelse(
      Z_corrected[m] >= 0, (1 - pnorm(Z_corrected[m])), pnorm(Z_corrected[m])
    )
    #p_corrected[m] <- 2 * (1 - pnorm(abs(Z_corrected[m])))
  }
  
  metabolite_scores <- tibble(metabolite = metNGenes,
                              k = n_microbe,
                              weighted_Zdirection = metZScores,
                              weighted_Zdirection_corrected = Z_corrected,
                              p_corrected = p_corrected) %>% 
    as.data.frame() %>% 
    arrange(p_corrected) %>%
    mutate(p_corrected = as.numeric(p_corrected)) %>% 
    left_join(., reaction %>% 
                select(exchangeRxns, equations), by = c("metabolite" = "exchangeRxns")) %>% 
    unique() %>%
    mutate(equations = sapply(strsplit(split = " <=> ",equations),`[`,1)) %>% 
    mutate(equations = sapply(strsplit(split = " => ",equations),`[`,1)) %>% 
    mutate(equations = gsub("\\[e\\]$","",equations))
  
  # summarize results
  # met.up <- c(network %>% filter(.data[[logFC]]  > 0) %>% filter(Type.A == "Metabolite") %>% pull(Vertex.A), 
  #             network %>% filter(.data[[logFC]]  > 0) %>% filter(Type.B == "Metabolite") %>% pull(Vertex.B)) %>% unique()
  # up.metabolite_scores <- metabolite_scores %>% filter(metabolite %in% met.up) 
  # 
  # met.down <- c(network %>% filter(.data[[logFC]]  < 0) %>% filter(Type.A == "Metabolite") %>% pull(Vertex.A), 
  #             network %>% filter(.data[[logFC]]  < 0) %>% filter(Type.B == "Metabolite") %>% pull(Vertex.B)) %>% unique()
  # down.metabolite_scores <- metabolite_scores %>% filter(metabolite %in% met.down) 
  
  up.metabolite_scores <- metabolite_scores %>% filter(weighted_Zdirection_corrected >= 0) 
  down.metabolite_scores <- metabolite_scores %>% filter(weighted_Zdirection_corrected < 0)
  
  return(list(all.top.met = metabolite_scores, up.met = up.metabolite_scores, down.met = down.metabolite_scores))
}

rma.res <- rma(network.uptake,pvalue = "pvalue",logFC ="log2FoldChange", reaction = fva.all1,abundance = mapped)
rma.res <- rma(network.uptake,pvalue = "pvalue",logFC ="log2FoldChange",reaction = fva.all1)
all.met <- rma.res[1] %>% as.data.frame()
up.met <- rma.res[2] %>% as.data.frame()
down.met <- rma.res[3] %>% as.data.frame()
```

