---
title: "ecGEMs"
author: "Xinmeng Liao"
date: "2025-04-02"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(xlsx)
library(ggpubr)
library(tidyr)
library(ggridges)
library(ggsignif)
library(DESeq2)
library(ComplexHeatmap)
library(colorRamp2)
library(tidyverse)
library(phyloseq)
library(vegan)
for (i in c("select","filter","mutate","rename","left_join")){
  conflicted::conflict_prefer(i,"dplyr")
}
conflicted::conflicts_prefer(stats::sd)

validation.sample <- read.xlsx("PD_Supplementary1.xlsx",sheetIndex = 2,header = T) %>% 
  mutate(ID = paste(Patient.ID, Visit.NO, sep = "_")) %>% 
  mutate(ID = gsub("TR","Feces_",ID)) %>% 
  mutate(ID = gsub(" ","", ID))
colnames(validation.sample) <- sub("\\.{2,}[a-zA-Z0-9].*", "",colnames(validation.sample))
colnames(validation.sample) <- sub("\\.$", "",colnames(validation.sample))
validation.sample$Insulin[which(validation.sample$Insulin == "<0.2")] = 0.1

study.sample <- read.xlsx("PD_Supplementary1.xlsx",sheetIndex = 3,header = T) %>% 
  mutate(ID = paste(Patient.ID, Visit.NO, sep = "_")) %>% 
  mutate(ID = gsub("TR","Feces_",ID)) %>% 
  mutate(ID = gsub(" ","", ID))
colnames(study.sample) <- sub("\\.{2,}[a-zA-Z0-9].*", "",colnames(study.sample))
colnames(study.sample) <- sub("\\.$", "",colnames(study.sample))
study.sample$Insulin[which(study.sample$Insulin == "<0.2")] = 0.1
samples <- list.files("stats/")
validation.files <- read.csv("/Users/xinmengliao/Documents/Project/20241117_CMA_PD_ecGEMs/validation.sample.txt",header = F,sep = "\t")
```

# 1. load DAs
```{r}
edger <- read.csv("DAs/edgeR.txt",header = T,sep = "\t")
deseq <- read.csv("DAs/DESeq2.txt",header = T,sep = "\t")
alde2 <- read.csv("DAs/ALDE2.txt",header = T,sep = "\t")
ancombc <- read.csv("DAs/ancombc.txt",header = T,sep = "\t")
wilcoxon <- read.csv("DAs/Wilcoxon_clr.txt",header = T,sep = "\t")
```

# 2. Create FVA network
```{r}
mapread <- read.csv("abundance/abundance.mapped.txt",header = T,sep = "\t") 
taxo.all <- read.csv('/Users/xinmengliao/Documents/Project/20241117_CMA_PD_ecGEMs/validation.taxo.txt',header = T,sep = "\t") %>% 
  mutate(species = sapply(strsplit(split = "s__",classification),`[`,2)) %>%  
  filter(!is.na(species))
fva.all <- read.csv('/Users/xinmengliao/Documents/Project/20241117_CMA_PD_ecGEMs/validation.fva.nozero.txt',sep = "\t",header = T)
#fva.all <- read.csv('/Users/xinmengliao/Documents/Project/20241117_CMA_PD_ecGEMs/validation.fva.all.txt',sep = "\t",header = T)

sample.list <- validation.files$V1
length(unique(fva.all$sample)) # should be 46
res <- edger

fva.all1 <- fva.all %>% 
  left_join(., taxo.all %>% select(user_genome, sample, classification), by  = c("sample","bin" = "user_genome")) %>% 
  filter(!is.na(classification)) %>% 
  left_join(., res,by = c("classification")) %>% distinct()

create.network <- function(data, pvalue, padj, log2fc){
  secrete <- data %>% filter(direction == "Secrete") %>%
    select(classification,exchangeRxns,direction,.data[[pvalue]],.data[[padj]],.data[[log2fc]])  %>% 
    unique() %>% 
    dplyr::rename(Vertex.A = classification, Vertex.B = exchangeRxns) %>% 
    mutate(Type.A = "Microbe", Type.B = "Metabolite")
  network <- data %>% filter(direction != "Secrete") %>% 
    select(exchangeRxns,classification,direction,.data[[pvalue]],.data[[padj]],.data[[log2fc]]) %>% 
    unique() %>% 
    dplyr::rename(Vertex.A = exchangeRxns, Vertex.B = classification) %>% 
    mutate(Type.A = "Metabolite", Type.B = "Microbe") %>% 
    rbind(., secrete) %>% 
    unique() %>% 
    filter(!is.na(.data[[padj]])) %>% 
    filter(Vertex.A != Vertex.B) %>% 
    group_by(edge_group = paste(pmin(Vertex.A, Vertex.B), pmax(Vertex.A, Vertex.B))) %>%
    filter(n() == 1) %>%  # 只保留不成对出现的边
    ungroup() %>% 
    select(-edge_group) %>% 
    select(Vertex.A, Type.A, Vertex.B, Type.B,everything())
  return(network)
}

network.all <- create.network(fva.all1,pvalue = "PValue",padj = "FDR",log2fc = "logFC")
network.uptake <- network.all %>% filter(direction == "Uptake")
```

# 3. Reporter metabolites
```{r}
rma <- function(network,pvalue,microbeFoldChanges = F,filter.extreme = F,reaction){
  
  rma.sub <- function(network,pvalue,filter.extreme = F,reaction){
  # change the microbe pvalue into z-score
  network <- network %>% 
    mutate(zscore = qnorm(1 - .data[[pvalue]])) %>%  
    mutate(zscore = ifelse(is.na(zscore), 0, zscore)) %>% 
    mutate(zscore = case_when(zscore == -Inf ~ -4,
                              zscore == Inf ~ 4, TRUE ~ zscore)) 
  
  if(filter.extreme == T){
    network <- network %>% filter(zscore!= -4 & zscore != 4)
  }
    
  # For each metabolite, find out the associated microbes
  mets <- unique(c(
    network %>% filter(Type.A == "Metabolite") %>% pull(Vertex.A),
    network %>% filter(Type.B == "Metabolite") %>% pull(Vertex.B)
  ))
  
  n_mets <- length(unique(mets))
  n_microbe <- rep(NA, n_mets)
  metZScores <- rep(NA, n_mets)
  metNGenes <- rep(NA, n_mets)
  meanZ <- rep(NA, n_mets)
  stdZ <- rep(NA, n_mets)
  microbe.zscore.list <- list()
  
  for (i in 1:n_mets){
    #print(i)
    met.network <- network %>% 
      filter(Vertex.A == mets[i] | Vertex.B == mets[i]) %>% unique()
    metZScores[i] <- sum(met.network$zscore) / sqrt(nrow(met.network))
    meanZ[i] <- mean(met.network$zscore)
    stdZ[i] <- sd(met.network$zscore)
    metNGenes[i] <- mets[i]
    n_microbe[i] <- nrow(met.network)
    microbe.zscore.list[[i]] <- met.network$zscore %>% unlist()
  }
  if (length(which(is.na(mets))) > 0){
    stop("Missing values found in 'mets'. Function terminated.")
  }
  
  set.seed(42)
  n_sim <- 1000
  all_zscores <- unlist(microbe.zscore.list)

  metabolite_scores <- tibble(metabolite = metNGenes,
                                  k = n_microbe,
                                  Z_raw = metZScores,
                                  gene_Zs = microbe.zscore.list)
  
  background_stats <- metabolite_scores %>%
    rowwise() %>% 
    mutate(background = list(replicate(n_sim, {
          mean(sample(all_zscores, k, replace = TRUE)) / sqrt(k)})),
          mu_k = mean(unlist(background)),
          sigma_k = sd(unlist(background)),
          Z_corrected = (Z_raw - mu_k) / sigma_k,
          p_corrected = 1 - pnorm(Z_corrected)
    ) %>% ungroup() %>%
    select(metabolite, k, Z_raw, Z_corrected, p_corrected)
  
  top_mets <- background_stats %>%
    arrange(p_corrected) %>%
    mutate(p_corrected = as.numeric(p_corrected)) %>% 
    left_join(., reaction %>% 
                select(exchangeRxns, equations), by = c("metabolite" = "exchangeRxns")) %>% 
    unique() %>%
    mutate(equations = sapply(strsplit(split = " <=> ",equations),`[`,1)) %>% 
    mutate(equations = sapply(strsplit(split = " => ",equations),`[`,1))
  }
  
  if(microbeFoldChanges == T){
    network.up <- network %>% 
      filter(logFC > 0)
    network.down <- network %>% 
      filter(logFC < 0) 
    met.up <- rma.sub(network.up,pvalue = "FDR",reaction = fva.all1,filter.extreme = T)
    met.down <- rma.sub(network.down,pvalue = "FDR",reaction = fva.all1,filter.extreme = T)
    return(list(all.met = top_mets, increased.met = met.up, decreased.met = met.down))
  }else{
    return(list(all.met = top_mets))
  }
}

rma.all <- rma(network.all,pvalue = "FDR",reaction = fva.all1,
               filter.extreme = T,microbeFoldChanges = T)
rma.uptake <- rma(network.uptake,pvalue = "FDR",reaction = fva.all1,
                  filter.extreme = T,microbeFoldChanges = T)

df1 <- rma.all[2] %>% as.data.frame()
df2<- rma.all[3] %>% as.data.frame()

```

